package tests;

import org.junit.Test;
import org.openqa.selenium.Cookie;
import utilities.TestBase;

import java.util.Set;

public class Day09_Cookies extends TestBase {
    /*
Cookies are temporary data that is generated by browser.
It's the way for a website to remember you, your preferences and your habits on web.
 */
    /*
        Given
                Go to "https://www.amazon.com"
        When
                Find the total number of cookies
        And
                Print all the cookies
        And
                Get the cookies by their name
        And
                Add new cookie
        And
                Delete cookie by name
        And
                Delete all the cookies
        */

    @Test
    public void cookieTest() throws InterruptedException {
        // Go to "https://www.amazon.com"
        driver.get("https://www.amazon.com");

        //Find the total number of cookies
        Set<Cookie> allCookies =driver.manage().getCookies();
        System.out.println("number of cookies= "+allCookies.size());

        //Print all the cookies
        for(Cookie eachCookie:allCookies){
            System.out.println("cookie: "+eachCookie);
            System.out.println("value: "+eachCookie.getValue());
            System.out.println("name: "+eachCookie.getName());
        }

        //Get the cookies by their name
        Cookie cookieNamed= driver.manage().getCookieNamed("ubid-main");
        System.out.println("cookie named: "+cookieNamed);

        //Add new cookie
        Cookie newCookie=new Cookie("my-cookie","apple-pie-cookie");
        driver.manage().addCookie(newCookie);
        Thread.sleep(2000);
        int numOfCookies= driver.manage().getCookies().size();
        System.out.println("number of cookies: "+numOfCookies);

        //Delete cookie by name
        driver.manage().deleteCookieNamed("ubid-main");
        System.out.println("number of cookies after delete: "+driver.manage().getCookies().size());

        //Delete all the cookies
        driver.manage().deleteAllCookies();
        System.out.println("number of cookies after delete all cookies: "+driver.manage().getCookies().size());






    }
}
